package telas;

import java.awt.Color;
import javax.swing.JOptionPane;
import mongodb.conectaMongo;

@SuppressWarnings({ "serial", "unused" })
public class cadastro extends javax.swing.JFrame {

	/**
	 * Creates new form RegisterScreen
	 */
	public cadastro() {
		setTitle("Cadastro - Battle of Mushroom's");
		initComponents();
		this.setResizable(false); // Não permite que a JFrame seja Maximizada/Redmensionada
		nometxt.setBackground(new java.awt.Color(0, 0, 0, 0));
		senhapss.setBackground(new java.awt.Color(0, 0, 0, 0));
		confsenhapss.setBackground(new java.awt.Color(0, 0, 0, 0));
		emailtxt.setBackground(new java.awt.Color(0, 0, 0, 0));
		cadastrar.setBackground(new java.awt.Color(0, 0, 0, 0));
		voltar.setBackground(new java.awt.Color(0, 0, 0, 0));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jCheckBox1 = new javax.swing.JCheckBox();
		emailtxt = new javax.swing.JTextField();
		nometxt = new javax.swing.JTextField();
		confsenhapss = new javax.swing.JPasswordField();
		senhapss = new javax.swing.JPasswordField();
		cadastrar = new javax.swing.JButton();
		voltar = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setLayout(null);

		jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
		jCheckBox1.setRolloverEnabled(false);
		jCheckBox1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open.png"))); // NOI18N
		jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox1ActionPerformed(evt);
			}
		});
		jPanel1.add(jCheckBox1);
		jCheckBox1.setBounds(780, 435, 30, 28);

		emailtxt.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
		emailtxt.setForeground(new java.awt.Color(0, 0, 0));
		emailtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		emailtxt.setBorder(null);
		jPanel1.add(emailtxt);
		emailtxt.setBounds(144, 422, 302, 55);

		nometxt.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
		nometxt.setForeground(new java.awt.Color(0, 0, 0));
		nometxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		nometxt.setBorder(null);
		nometxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
		nometxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				nometxtActionPerformed(evt);
			}
		});
		jPanel1.add(nometxt);
		nometxt.setBounds(144, 319, 302, 55);

		confsenhapss.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
		confsenhapss.setForeground(new java.awt.Color(0, 0, 0));
		confsenhapss.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		confsenhapss.setBorder(null);
		confsenhapss.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
		jPanel1.add(confsenhapss);
		confsenhapss.setBounds(514, 422, 302, 55);

		senhapss.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
		senhapss.setForeground(new java.awt.Color(0, 0, 0));
		senhapss.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		senhapss.setBorder(null);
		jPanel1.add(senhapss);
		senhapss.setBounds(514, 319, 302, 55);

		cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		cadastrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cadastrarActionPerformed(evt);
			}
		});
		jPanel1.add(cadastrar);
		cadastrar.setBounds(320, 525, 302, 51);

		voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		voltar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				voltarActionPerformed(evt);
			}
		});
		jPanel1.add(voltar);
		voltar.setBounds(817, 27, 137, 43);

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.jpg"))); // NOI18N
		jPanel1.add(jLabel1);
		jLabel1.setBounds(0, 0, 960, 770);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void nometxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_nometxtActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_nometxtActionPerformed

	private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cadastrarActionPerformed
		conectaMongo conn = new conectaMongo();
		String nome = nometxt.getText();
		String email = emailtxt.getText();
		@SuppressWarnings("deprecation")
		String senha = senhapss.getText();
		@SuppressWarnings("deprecation")
		String confsenha = confsenhapss.getText();

		boolean emailcorreto = conn.findValuesSignUP(email);

		if (emailcorreto == false) {
			if (senha.equals(confsenha)) {
				conn.insertValue(nome, email, senha);
				JOptionPane.showMessageDialog(null, "Email cadastrado! Divirta-se!");
				dispose();
				new login().setVisible(true);
			} else {
				JOptionPane.showMessageDialog(null, "Senhas diferentes!! Tente novamente!!", "Erro ao cadastrar-se!",
						JOptionPane.WARNING_MESSAGE);
			}
		}
	}// GEN-LAST:event_cadastrarActionPerformed

	private void voltarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_voltarActionPerformed
		// TODO add your handling code here:
		dispose();
		new login().setVisible(true);
	}// GEN-LAST:event_voltarActionPerformed

	private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox1ActionPerformed
		if (jCheckBox1.isSelected()) {
			senhapss.setEchoChar((char) 0); // Mostra a senha
			confsenhapss.setEchoChar((char) 0); // Mostra a senha
		} else {
			senhapss.setEchoChar('\u2022'); // Esconde a senha com pontos
			confsenhapss.setEchoChar('\u2022'); // Esconde a senha com pontos
		}
	}// GEN-LAST:event_jCheckBox1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new cadastro().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton cadastrar;
	private javax.swing.JPasswordField confsenhapss;
	private javax.swing.JTextField emailtxt;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField nometxt;
	private javax.swing.JPasswordField senhapss;
	private javax.swing.JButton voltar;
	// End of variables declaration//GEN-END:variables
}
