	package telas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import main.GamePanel;
import mongodb.conectaMongo;

@SuppressWarnings("serial")
public class login extends javax.swing.JFrame {

	/**
	 * Creates new form LoginScreen
	 */
	public login() {
		setTitle("Login - Battle of Mushroom's");
		initComponents();
		this.setResizable(false); // Não permite que a JFrame seja Maximizada/Redmensionada
		senhapss.setBackground(new java.awt.Color(0, 0, 0, 0));
		emailtxt.setBackground(new java.awt.Color(0, 0, 0, 0));
		cadastre_se.setBackground(new java.awt.Color(0, 0, 0, 0));
		entrar.setBackground(new java.awt.Color(0, 0, 0, 0));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jCheckBox1 = new javax.swing.JCheckBox();
		cadastre_se = new javax.swing.JButton();
		entrar = new javax.swing.JButton();
		senhapss = new javax.swing.JPasswordField();
		emailtxt = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setLayout(null);

		jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
		jCheckBox1.setRolloverEnabled(false);
		jCheckBox1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/open.png"))); // NOI18N
		jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox1ActionPerformed(evt);
			}
		});
		jPanel1.add(jCheckBox1);
		jCheckBox1.setBounds(590, 405, 30, 28);

		cadastre_se.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		cadastre_se.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cadastre_seActionPerformed(evt);
			}
		});
		jPanel1.add(cadastre_se);
		cadastre_se.setBounds(329, 542, 302, 51);

		entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		entrar.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				entrarActionPerformed(evt);
			}
		});
		jPanel1.add(entrar);
		entrar.setBounds(329, 469, 302, 51);

		senhapss.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
		senhapss.setForeground(new java.awt.Color(0, 0, 0));
		senhapss.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		senhapss.setBorder(null);
		jPanel1.add(senhapss);
		senhapss.setBounds(329, 391, 302, 55);

		emailtxt.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
		emailtxt.setForeground(new java.awt.Color(0, 0, 0));
		emailtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		emailtxt.setBorder(null);
		jPanel1.add(emailtxt);
		emailtxt.setBounds(329, 300, 302, 55);

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.jpg"))); // NOI18N
		jPanel1.add(jLabel1);
		jLabel1.setBounds(0, 0, 960, 770);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void cadastre_seActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cadastre_seActionPerformed
		dispose();
		new cadastro().setVisible(true);
	}// GEN-LAST:event_cadastre_seActionPerformed

	private void entrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_entrarActionPerformed
		conectaMongo conn = new conectaMongo();
		String email = emailtxt.getText();
		@SuppressWarnings("deprecation")
		String senha = senhapss.getText();

		boolean emailVer = conn.findValuesSignINEmail(email);
		boolean senhaVer = conn.findValuesSignINSenha(senha);

		if ((senhaVer == true) && (emailVer == true)) {
			JOptionPane.showMessageDialog(null, "Seja Bem-Vindo");
			dispose();

			// Iniciando o Jogo
			JFrame window = new JFrame();
			window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
			window.setResizable(false);
			window.setTitle("Battle of Mushroom's");

			GamePanel gamePanel = new GamePanel();
			window.add(gamePanel);
			window.pack();

			window.setLocationRelativeTo(null);
			window.setVisible(true);

			gamePanel.setupGame();
			gamePanel.startGameThread();
		} else {
			JOptionPane.showMessageDialog(null, "Email ou Senha Incorretos!", "Erro ao Entrar", JOptionPane.OK_OPTION);
		}
	}// GEN-LAST:event_entrarActionPerformed

	private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jCheckBox1ActionPerformed
		if (jCheckBox1.isSelected()) {
			senhapss.setEchoChar((char) 0); // Mostra a senha
		} else {
			senhapss.setEchoChar('\u2022'); // Esconde a senha com pontos
		}

	}// GEN-LAST:event_jCheckBox1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new login().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton cadastre_se;
	private javax.swing.JTextField emailtxt;
	private javax.swing.JButton entrar;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPasswordField senhapss;
	// End of variables declaration//GEN-END:variables
}
